#!/usr/bin/env bash
# debugging skills, find out what’s keeping your Ubuntu
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
