#!/usr/bin/env bash
if [ $# -ne 1 ];
then
        echo "Usage: manage_my_process {start|stop|restart}"
elif [[ $1 == "start" ]];
then

        ./manage_my_process &
        pid=$!
        echo "$pid" > /var/run/my_process.pid
        echo "manage_my_process started"
elif [[ $1 == "stop" ]];
then
   
        if [ -f /var/run/my_process.pid ];
        then
                pid=$(cat /var/run/my_process.pid)
                kill $pid
        fi
        rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [[ $1 == "restart" ]];
then
        
        pid=$(cat /var/run/my_process.pid)
        kill $pid
        rm /var/run/my_process.pid
        ./manage_my_process &
        pid=$!
        echo "$pid" > /var/run/my_process.pid
        echo "manage_my_process restarted"
fi
