#!/usr/bin/env bash
# the fizzbuzz task
count=1
while [ $count -lt 101 ]
do
	fizz=$((count % 3))
	buzz=$((count % 5))

	if [ $fizz -lt 1 ] && [ $buzz -lt 1 ]
        then
                echo "FizzBuzz"
	elif [ $fizz -lt 1 ]
	then
		echo "Fizz"
	elif [ $buzz -lt 1 ]
	then
		echo "Buzz"
	else
		echo "$count"
	fi
	((count++))
done
