#!/usr/bin/env bash
# configuring firewall to block incoming traffic

sudo apt-get -y update
sudo apt-get install -y ufw
ufw disable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable

